"""Generate lib/Engine_Choir.sc (the norns engine) from sc/angel.scd, so the
engine always sings with exactly the same voice as the desktop version.

    python3 tools/build_engine.py
"""
import os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = open(os.path.join(ROOT, 'sc/angel.scd')).read()

def between(text, start, end):
    i = text.index(start); j = text.index(end, i)
    return text[i:j]

defaults = between(src, '~angelDefaults = (', ');') + ');'
vowels = between(src, '~angelVowels = [', '];') + '];'
voice = between(src, 'SynthDef(\\angel, {', '\n\t}),') + '\n\t})'
room = between(src, 'SynthDef(\\angelRoom, {', '\n\t}),') + '\n\t})'

defaults = defaults.replace('~angelDefaults = (', 'd = (')
vowels = vowels.replace('~angelVowels = [', 'vowels = [').replace('~angelDefaults', 'd')
voice = voice.replace('\t\tvar d = ~angelDefaults;\n', '').replace('~angelVowels', 'vowels')

def indent(block, n=1):
    return '\n'.join(('\t' * n + l) if l.strip() else l for l in block.split('\n'))

engine = f'''// 13 angels — norns engine.
//
// GENERATED by tools/build_engine.py from sc/angel.scd — edit that file and
// re-run the script instead of editing this one.
//
// The "angel" voice is modelled on the intro of A Silver Mt. Zion's
// "13 Angels Standing Guard 'Round The Side Of Your Bed" (see sc/angel.scd
// and analysis/ for how it was measured and tuned against the record).
//
// Vowels: 0 angel ("Ah" -> "u"), 1 a, 2 eh, 3 ih, 4 oh, 5 uh. Each note
// morphs from `vow` to `vow2` over `delay` seconds. Releasing a note makes
// it sigh down and stop.
//
// Originally a vowel synth by Matias Monteagudo (2020):
// https://patchstorage.com/mm-vowels-synth/

Engine_Choir : CroneEngine {{
	var pg, fxBus, room;
	var amp = 0.5;
	var delay = 0.3;
	var fall = 3;
	var fallTime = 0.5;
	var breath = nil;
	var notes;

	*new {{ arg context, doneCallback;
		^super.new(context, doneCallback);
	}}

	alloc {{
		var d, vowels;
{indent(defaults, 2)}
{indent(vowels, 2)}

		notes = Dictionary.new;
		pg = ParGroup.head(context.xg);
		fxBus = Bus.audio(context.server, 2);

{indent(voice, 1)}.add;

{indent(room, 1)}.add;

		context.server.sync;
		room = Synth.tail(context.xg, \\angelRoom, [\\in, fxBus, \\out, context.out_b]);

		this.addCommand("noteOn", "ffii", {{ arg msg;
			var hz = msg[1], vel = msg[2], args;
			// a re-struck note sighs out while the new one starts
			notes.removeAt(hz) !? {{ |old| old.set(\\gate, 0) }};
			args = [
				\\out, fxBus, \\freq, hz, \\amp, 0.2 * amp * vel,
				\\vow, msg[3], \\vow2, msg[4], \\morph, delay,
				\\fall, fall, \\fallTime, fallTime,
			];
			breath !? {{ args = args ++ [\\breath, breath] }};
			notes.put(hz, Synth.new(\\angel, args, pg));
		}});

		this.addCommand("noteOff", "f", {{ arg msg;
			notes.removeAt(msg[1]) !? {{ |synth| synth.set(\\gate, 0) }};
		}});

		this.addCommand("amp", "f", {{ arg msg; amp = msg[1] }});
		this.addCommand("delay", "f", {{ arg msg; delay = msg[1] }});
		this.addCommand("fall", "f", {{ arg msg; fall = msg[1] }});
		this.addCommand("fallTime", "f", {{ arg msg; fallTime = msg[1] }});
		this.addCommand("breath", "f", {{ arg msg; breath = msg[1] }});
		this.addCommand("room", "f", {{ arg msg; room.set(\\mix, msg[1]) }});
	}}

	// Free the playing notes and the engine on exit.
	free {{
		notes.do(_.free);
		pg.free;
		room.free;
		fxBus.free;
	}}
}}
'''
open(os.path.join(ROOT, 'lib/Engine_Choir.sc'), 'w').write(engine)
print('wrote lib/Engine_Choir.sc')
